### ISSUE TITLE
App Crash and Freeze

### ISSUE THREAD

**Issue by Omnius1234** [beyondcode/tinkerwell-community#406] opened 2021-03-16 19:17 UTC
When i open Tinkerwell,the app crash and freeze

**Comment by sschlein** [comment] 2021-03-17 08:35
Which operating and Tinkerwell version do you use?

This is the first time that someone mentions this

**Comment by Omnius1234** [comment] 2021-03-18 19:13
i'm using the version 2.12.1,
the problem appears when i open a php file but not always,
when i open some php file,the app crash and freeze and i can't write or do anything

**Comment by mpociot** [comment] 2021-03-19 09:43
Can you tell me the operating system you use?
I'm also unable to reproduce the issue - and "but not always" is always hard to reproduce 😅

**Comment by Omnius1234** [comment] 2021-03-20 12:23
windows 10  20H2 19042 ,you're right too 😅 but that's all

**Comment by Omnius1234** [comment] 2021-03-20 13:00
how can i help debug that?

**Comment by mpociot** [comment] 2021-04-26 10:39
This should be fixed with the latest version (2.13.0)

**Closed by mpociot** 2021-04-26 10:39 UTC
Labels: bug
