### ISSUE TITLE
PHP Fatal error:  Cannot declare class Spatie\WordPressRay\Symfony\Component\*, because the name is already in use

### ISSUE THREAD

**Issue by slaFFik** [beyondcode/tinkerwell-community#395] opened 2021-01-31 16:48 UTC
Steps to reproduce:

1. Create a local WordPress 5.6 installation
2. Install a [Spatie Ray](https://wordpress.org/plugins/spatie-ray/) plugin v1.2.2 inside WP.
3. Open Tinkerwell v2.11.0 (or whatever is the latest) and select a directory where your WP installation from step 1 is located.
4. In the Tinkerwell code section enter `home_url();`, for example.
5. In the Tinkerwell preview section you will see an HTML output of the "fatal error happened" WordPress page.
6. Open your local error log for this site. You will see this:
```
[31-Jan-2021 15:22:19 UTC] PHP Fatal error:  Cannot declare class Spatie\WordPressRay\Symfony\Component\VarDumper\Dumper\AbstractDumper, because the name is already in use in ...\wp-content\plugins\spatie-ray\vendor\symfony\var-dumper\Dumper\AbstractDumper.php on line 22
```

A similar issue (`Fatal error: Cannot declare class Spatie\WordPressRay\Symfony\Component\Console\Output\Output`) has been previously reported by @jeffreyvr in the `wordpress-ray` repository by @freekmurze: https://github.com/spatie/wordpress-ray/issues/8. Here is a received reply:
> I consider this more an issue on Tinkerwell's part, as this package is working fine in WordPress.

Ray is working fine without generating any errors. The error log entry is created only when running the code inside the Tinkerwell app.

**Comment by jeffchown** [comment] 2021-02-20 21:39
Hi @slaFFik - I've been trying to setup my dev environment to use the same tools (Ray, Tinkerwell, etc.) across all of my Laravel and Wordpress work and ran into the same error you described above when working on a Wordpress project.

As I want to be able to use Ray to help me debug my custom Wordpress plugins, I've installed Ray in my `/wp-content/mu-plugins` folder as instructed here https://spatie.be/docs/ray/v1/installation-in-your-project/wordpress#must-use-plugins

After some digging and a little experimentation, I found that, changing my `/wp-content/mu-plugins/ray-loader.php` file fixed the error and allowed me to use Ray and Tinkerwell together successfully with Wordpress :).

My new `/wp-content/mu-plugins/ray-loader.php` file contents are as follows:

```php
<?php

if (class_exists('LaravelTinkerwellDriver')) {
    if (! function_exists('ray')) {
        function ray() {}
    }
} else {
    require WPMU_PLUGIN_DIR.'/wordpress-ray/wp-ray.php';
}
```

Hope this helps anyone else who finds Ray and Tinkerwell as useful as I do.

**Comment by mpociot** [comment] 2021-03-19 10:01
I haven't found a proper way to pin down the cause of this issue yet, so please use the provided workaround from @jeffchown in the meantime.

**Comment by therajumandapati** [comment] 2021-04-16 19:49
@jeffchown Appreciate the hotfix idea, but it doesn't seem to be working even when I changed `if (class_exists('LaravelTinkerwellDriver')) {` to `if (class_exists('WordpressTinkerwellDriver')) {`. Thoughts?

**Comment by therajumandapati** [comment] 2021-04-16 19:53
@jeffchown NVM, I wanted to have Ray WP plugin auto-update, so it's actually in the `/plugins` folder, that's why this wasn't working. Fixed it by moving it to `/mu-plugins`, thanks!

**Comment by jeffreyvr** [comment] 2021-05-25 09:53
In version 1.3.2 of WordPress Ray this issue is resolved.

**Closed** 2021-05-25 09:55 UTC
Labels: bug
