### ISSUE TITLE
Idea: Export Output to csv/json/etc

### ISSUE THREAD

**Issue by apocalyarts** [beyondcode/tinkerwell-community#378] opened 2021-01-16 16:13 UTC
My boss sometimes "wants to know stuff". His requests often are translatable to a custom SQL query, so I usually spin up Tailwind, connect to our sever via SSH and tinker with Eloquent to fetch the results. 

This is extremely convenient and already saved me dozens of hours. However, I always struggle when it comes to storing the query results. I usually paste Tailwinds output into sublime and do some find/replace until I have a valid csv file that I can pass to my boss.

It would be cool, if Tailwind would offer me a button that let's me export the output from the right side to a file.

**Comment by mitchazj** [comment] 2021-01-18 04:16
I think you meant Tinkerwell, not Tailwind? Two very different projects :) definitely like this idea though!

**Comment by apocalyarts** [comment] 2021-01-18 06:11
Oh yes, weird typo 😀 don’t know where my mind was 😀

**Comment by squatto** [comment] 2021-02-11 08:37
Possible duplicate of #221

Have you used the "Table" mode in Tinkerwell? I think it will do exactly what you're looking for:

![image](https://user-images.githubusercontent.com/748444/107615588-adb8b180-6c09-11eb-90fd-6aede796e8ce.png)

In the menu go to Tinker Mode > Table to switch to it.

**Comment by mpociot** [comment] 2021-02-25 10:25
Yup. I think the Table mode is what you're looking for. If you need more advanced Eloquent features, you might want to check out [Invoker](https://invoker.dev) which also allows you to export data and contains a Tinkerwell plugin

**Closed by mpociot** 2021-02-25 10:25 UTC
