### ISSUE TITLE
On Mac, look for Homebrew PHP binary first

### ISSUE THREAD

**Issue by sailorsteve** [beyondcode/tinkerwell-community#115] opened 2020-02-25 21:33 UTC
After installing Tinkerwell on my Mac, I was getting strange Symfony error messages when running a local Laravel app in Tinkerwell. This was caused because Tinkerwell defaulted to using the Mac system PHP binary at /usr/bin/php which is version 7.1.33 on my Mac. On Macs, could you default to using the Homebrew PHP binary (at /usr/local/bin/php) if it is present?

**Comment by squatto** [comment] 2020-05-06 03:24
Linking #161 because it's caused by the same issue

**Comment by mpociot** [comment] 2020-05-06 10:06
I actually already use "which php" on Mac to detect the correct binary, but sometimes it doesn't work.
I've changed that to actually just check for the homebrew path if present and use that one instead. Will be in the next version!

**Closed by mpociot** 2020-05-06 10:06 UTC

**Comment by rockymontana** [comment] 2020-05-25 10:09
I still get this in 2.7.0 @mpociot 
Should this have been fixed in <=2.7.0?
