### ISSUE TITLE
Tinkerwell stopped working after update to v2.6.0

### ISSUE THREAD

**Issue by dabonzo** [beyondcode/tinkerwell-community#199] opened 2020-04-26 22:52 UTC
A simple App\User::first(); stops with
```php
PHP Fatal error:  Uncaught Error: Call to undefined function _PhpScoperc223a629f245\posix_getpwuid() in phar:///tmp/.mount_TinkerOmjhQN/resources/tinkerwell/tinker.phar/index.php:32
Stack trace:
#0 /tmp/.mount_TinkerOmjhQN/resources/tinkerwell/tinker.phar(14): require()
#1 {main}
  thrown in phar:///tmp/.mount_TinkerOmjhQN/resources/tinkerwell/tinker.phar/index.php on line 32```

PHP v: 7.4.5 and set
Framework: Laravel 7 
Working directory set to Laravel root dierctory

**Comment by dabonzo** [comment] 2020-04-28 21:35
Is there at least some place where I can download old versions. They worked. Unfortunately I don't have any old versions anymore

**Comment by mikeerickson** [comment] 2020-04-29 01:17
Just an idea, but make sure tour PHP binary is accurate. This has proven to be the cause of many many issues with Tinkerwell (I have been bit by it during numerous updates)

There is mention of this on their support page (I don’t have the link handy at the moment$

**Comment by nickknissen** [comment] 2020-04-29 07:48
You can change the version of the URL `Tinkerwell%20Setup%202.6.0.exe` to `Tinkerwell%20Setup%202.5.0.exe` for version 2.5.0

**Comment by dabonzo** [comment] 2020-04-29 08:19
@mikeerickson  php version seems OK, v2.5.0 works with the same settings, v2.6.0 doesn't.
@nickknissen Thanks Nick, it worked. I can now work with the old version. The new version (2.6.0) still quits with the same error message

**Comment by mpociot** [comment] 2020-05-06 09:44
This will be fixed in the next release. Version 2.6.0 allows registration of global drivers and therefore uses the posix methods to detect the user home directory.
I added some checks to see if those methods exist and ignore the global driver location otherwise

**Closed by mpociot** 2020-05-06 09:44 UTC
