### ISSUE TITLE
[Bug]: plugin stopped working in phpstorm 2022.1

### ISSUE THREAD

**Issue by gandesc** [beyondcode/tinkerwell-community#572] opened 2022-04-19 07:03 UTC
### Operating system

Linux Mint 19.3 Tricia, MATE 1.22.2

### Laravel Version

v9.8.1

### PHP Version

PHP 8.0.17 (cli) (built: Mar 20 2022 17:03:50) ( NTS )

### Project Location

Local

### Bug description

After upgrading PhpStorm from 2021.3 to the next available version (2022.1), the "Run with Tinkerwell" command no longer works.

When starting PhpStrom from commandline, after trying to run some code with tinkerwell, I can see an exception in the terminal, see below.

The other two options, "Inspect with Tinkerwell" & "Show table with Tinkerwell" seem to work and no errors are visible in the terminal.

### Steps to reproduce

open a file, write a simple line to print to log, select the line and run it with tinkerwell.

### Relevant log output

```shell
2022-04-19 09:50:56,444 [  21795] SEVERE - #c.i.i.p.PluginManager - null
java.lang.NullPointerException
	at TinkerwellRunner.runCode(TinkerwellRunner.java:47)
	at RunWithTinkerwellAction.actionPerformed(RunWithTinkerwellAction.java:73)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:579)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$11(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:701)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:590)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:473)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:462)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:227)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2022-04-19 09:50:56,446 [  21797] SEVERE - #c.i.i.p.PluginManager - PhpStorm 2022.1  Build #PS-221.5080.224
2022-04-19 09:50:56,446 [  21797] SEVERE - #c.i.i.p.PluginManager - JDK: 11.0.14.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-04-19 09:50:56,446 [  21797] SEVERE - #c.i.i.p.PluginManager - OS: Linux
```

**Comment by okaufmann** [comment] 2022-04-19 20:46
I have the exact same problem using PHPStorm 2022.1 on macOS 12.3.1 on a MacBook Pro 14" with M1Pro

**Comment by okaufmann** [comment] 2022-04-19 20:48
Seems like this is duplicate of https://github.com/beyondcode/tinkerwell-community/issues/571 (Same Problem after upgrade to 2022.1)

**Comment by sschlein** [comment] 2022-04-20 08:41
This is a duplicate of https://github.com/beyondcode/tinkerwell-community/issues/571

**Closed by sschlein** 2022-04-20 08:41 UTC
