### ISSUE TITLE
Not working with Homestead and Laravel 5.2 - Call to undefined method Psy\Shell::getBoundObject()

### ISSUE THREAD

**Issue by igorsgm** [beyondcode/tinkerwell-community#402] opened 2021-02-18 05:18 UTC
- TW2.12.1
- Homestead and Laravel 5.2
- "*php artisan tinker*": `Psy Shell v0.7.2 (PHP 7.3.6-1+ubuntu18.04.1+deb.sury.org+1 — cli) by Justin Hileman`

![Screen Shot 2021-02-17 at 3 56 50 PM](https://user-images.githubusercontent.com/14129843/108283771-c0b31080-7138-11eb-9448-6fc443981f90.png)

`CustomErrorException with message 'PHP Error:  Call to undefined method Psy\Shell::getBoundObject() in phar:///tmp/tinker_compressed.phar/vendor/psy/psysh/src/ExecutionClosure.php on line 81'`

But testing in another project that is on Laravel 7 inside the same Homestead, works fine.

@mpociot Could you please advise?

**Comment by tecnoe** [comment] 2021-02-26 14:37
Windows 10.
Laravel 5.2
PHP 7.1

![image](https://user-images.githubusercontent.com/10902293/109313394-c92cda80-780d-11eb-819d-783409a17cd3.png)

**Comment by mpociot** [comment] 2021-03-19 09:50
I'll close this as it's a duplicate of #368

**Closed by mpociot** 2021-03-19 09:50 UTC
