### ISSUE TITLE
Unable to SSH two different users in same server

### ISSUE THREAD

**Issue by joseballester** [beyondcode/tinkerwell-community#355] opened 2020-12-04 11:16 UTC
We are two users trying to run Tinkerwell via SSH in the same server, each one with their user. After user 1 has run a command successfully, user 2 is able to log in (no SSH error is returned) but Tinkerwell hangs when running the commands.

After exploring a bit, I understand that Tinkerwell copies some `tinker.txt` and `tinker_compressed.phar` files to the server's `/tmp` folder via SFTP, which are then owned by the first user who runs Tinkerwell. As the files are not removed after being used, user 2 tries to do the same but `/tmp/tinker.txt` and `/tmp/tinker_compressed.phar` paths are already used and owned by somebody else, and therefore cannot continue. 

As a result, Tinkerwell hangs and cannot execute the given commands (on the client side) and the SFTP process `/usr/lib/openssh/sftp-server` hangs (on the server side).

This can be solved by removing the `/tmp/tinker.txt` and `/tmp/tinker_compressed.phar` files after using them. Maybe Tinkerwell could do it when closing a session or (maybe better) it could use different temporary paths for each user?

Thanks!

**Comment by njames** [comment] 2020-12-06 22:51
Similar to #264

**Comment by mpociot** [comment] 2021-03-19 15:59
I'll close this as a duplicate of #264

**Closed by mpociot** 2021-03-19 15:59 UTC
