### ISSUE TITLE
Failed to update new version on Ubuntu 20.04

### ISSUE THREAD

**Issue by manish-manghwani** [beyondcode/tinkerwell-community#292] opened 2020-09-03 13:08 UTC
Starting Tinkerwell leads to following prompt.

![image](https://user-images.githubusercontent.com/17725637/92118725-7ea94300-ee14-11ea-867c-96ac072a6429.png)

On restarting the app again, it doesn't update and throws back the same prompt.

Currently I am using Ubuntu 20.04

**Comment by mpociot** [comment] 2020-09-08 11:08
Does it make a difference if you leave the app closed a little bit longer?
Usually the problem is that the application is still updating in the background.

**Comment by manish-manghwani** [comment] 2020-09-08 12:10
Hi Marcel,

I have left it for couple of hours, so that it can upgrade in background. but it seems like it isn't updating. 

Also, the only option was to remove the app Image and replace it with latest one.

**Comment by manish-manghwani** [comment] 2020-09-16 18:19
Should I close this issue or anyone is looking into it?

**Comment by Maidomax** [comment] 2020-09-30 16:27
Same here. Even if I close it and come back to it tomorrow.

**Comment by mpociot** [comment] 2021-04-08 10:27
I'm closing this as it's a duplicate of #314

**Closed by mpociot** 2021-04-08 10:27 UTC
