### ISSUE TITLE
SSH Config

### ISSUE THREAD

**Issue by reed-jones** [beyondcode/tinkerwell-community#137] opened 2020-03-07 02:22 UTC
It would be great if it could read remote ssh connection details from the ssh config. https://www.ssh.com/ssh/config

**Comment by tanshiqi** [comment] 2020-03-18 10:52
Need this feature. Especially SSH tunneling to access restricted servers

**Comment by mpociot** [comment] 2020-09-07 14:29
Closing this, as it's basically a duplicate of #14

**Closed by mpociot** 2020-09-07 14:29 UTC
