### ISSUE TITLE
Query inspector key binding not working 

### ISSUE THREAD

**Issue by Wulfheart** [beyondcode/tinkerwell-community#332] opened 2020-11-09 09:24 UTC
From the tinkewell documentation at https://beyondco.de/docs/tinkerwell/advanced-usage/query-inspection:
> To use this feature, select the code snippet that you want to inspect the Eloquent queries in and press Cmd/Ctrl+Shift+R. This will evaluate your code and the output panel will show you all queries that were executed in your highlighted code snippet, including all query bindings that were used.

When selecting a query and pressing `Control + Shift + R` I'm getting a prompt to replace something. I don't want to replace anything, I just want to inspect my Laravel 8 application's queries.
![grafik](https://user-images.githubusercontent.com/25671390/98523014-adf58980-2275-11eb-9fb4-1d2f1a6e1168.png)

**Comment by sschlein** [comment] 2020-11-09 09:25
Duplicate of https://github.com/beyondcode/tinkerwell-community/issues/302 :)

**Closed by sschlein** 2020-11-09 09:25 UTC
